# Tensorとは？
---
前単元まで`Tensor`の特徴を学んだ。  
この単元ではTensorを利用する上で利用頻度が高い、関数などを学んでいこう！


## この単元の目標

* transposeの利用方法を学ぶ
* reshapeの利用方法を学ぶ
* zero_の利用方法を学ぶ

  → **Tensor型でよく利用する関数について勉強していこう**

In [ ]:
# pytorchライブラリのインポート
import torch

## Tensorを操作する関数
---
PyTorchでTensorを扱う際に利用頻度が高い、`transpose`と`reshape`の使い方を見ていこう

それぞれの関数の働きは
* `transpose`：**行列の転置**
* `reshape`：**行列の形（サイズ）の変更**

一つずつ体験していこう。

---
【例題1】プログラムを実行して実行結果から挙動を確かめよう。

In [ ]:
x = torch.rand((4, 3))
print(x)
print(x.transpose(0, 1))

tensor([[0.3353, 0.8688, 0.4435],
        [0.3135, 0.5146, 0.0721],
        [0.7371, 0.2581, 0.8868],
        [0.6382, 0.5075, 0.6453]])
tensor([[0.3353, 0.3135, 0.7371, 0.6382],
        [0.8688, 0.5146, 0.2581, 0.5075],
        [0.4435, 0.0721, 0.8868, 0.6453]])


---
4行3列の行列から3行4列の行列へ転置をすることができた。

* `Tensor名.transpose(0, 1)`で転置することができる
    * `torch.t(Tensor名)`でも同様の動作となる
    
**注意**
* NumPyのtransposeとは処理が違うので混同しないように注意が必要

---
【例題2】プログラムを実行して実行結果から挙動を確かめよう。

In [ ]:
x = torch.ones(16)
print(x)
print(x.reshape(2, 8))
print(x.reshape(4, -1))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


---
要素を変えずに形状だけ変えることができた。

* `Tensor名.reshape(行, 列)`で形状を指定できる
    * 行や列の引数に`-1`を指定することで他方の次元の長さに合わせて自動で形状変換が可能。
    
---
【問題】Tensor`[[1,1,1], [1,2,2], [2,2,3], [3,3,3]]`を宣言した後，3行に形状変換して表示しよう。

In [ ]:
y = torch.tensor([[1,1,1],[1,2,2],[2,2,3],[3,3,3]])
print(y.reshape(3, -1))

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])


- ```
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])
```
と表示されていれば成功だ。

## Tensorを操作する関数2
---
次は`zero_()`を紹介する。

関数の働きは
* `zero_()`：**行列の全ての要素を0にする**


---
【例題】プログラムを実行して実行結果から挙動を確かめよう。

In [ ]:
a = torch.tensor([[1,2,3],[4,5,6]]) # 手動作成
print(a)
a.zero_()# 中身をゼロ埋めにする
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[0, 0, 0],
        [0, 0, 0]])


---
上記のプログラムのように、変数の値を残さず変更することを**インプレース(破壊的メソッド)**と呼ぶ。
* PyTorchではインプレースで変更する関数には**_**が利用されているので注意して利用しよう。

---
【問題】Tensor`[[1,1,1], [1,2,2], [2,2,3], [3,3,3]]`を宣言した後、zero_()を利用して要素を全て0にして表示しよう。

In [ ]:
t1 = torch.tensor([[1,1,1],[1,2,2],[2,2,3],[3,3,3]])
print(t1.zero_())

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


- ```
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
```
と表示されていれば成功だ．